version: '3'
services:
  app:
    build: .
    container_name: "studentquiz"
    ports:
      - 9000:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod