spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017

security:
  oauth2:
    client:
      id: 'studentquiz-client'
      secret: 'jo709FR49Ft8ft589TF8265fyf595ftY'
    resource:
      id: 'studentquiz-resource-server'